apiVersion: v2
description: Automated Kubernetes monitoring
icon: https://logicmonitor.github.io/helm-charts-qa/lm_logo.png
kubeVersion: '>= 1.16.0-0'
maintainers:
  - email: argus@logicmonitor.com
    name: LogicMonitor
name: argus
version: 8.3.0-rc02
home: https://logicmonitor.github.io/helm-charts-qa
appVersion: v12.4.0-rc01
dependencies:
  - name: lmutil
    repository: https://logicmonitor.github.io/helm-charts-qa
    # repository: file://../lmutil
    version: 0.1.9
